export enum ActionTypesEnum {
  LOGIN = "INICIO DE SESIÓN",
  CREATE_USER = "CREACIÓN DE USUARIO",
  UPDATE_USER = "ACTUALIZACIÓN DATOS DE USUARIO",
  BAN_USER = "BANEAR USUARIO",
  UNBAN_USER = "DESBANEAR USUARIO",
}
